---
title: "Bagging Model"
author: "Oriana Meldrum"
date: "11/30/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Bagging model

```{r}
#Set up
#reproducibility
set.seed(445)


library(ISLR)
library(tidyr)
library(dplyr)
library(knitr)
library(tree)
library(randomForest) # random forests & bagging

library(readr)


#60/40 split
train <-read.csv("train.csv")
test <- read.csv("test.csv")


```

```{r}
bagging <- randomForest(HeartDisease ~ .,data = train, mtry = 19, ntree = 500, type = "class", 
                        importance = TRUE,
                        proximity = TRUE) 




#Confusion Matrix
predict_bag <- predict(bagging, newdata = test)
predicted_bag <- ifelse(predict_bag>0.5,1,0)
confm_bag<-table(predict_bag,test$HeartDisease)
confm_bag

#MSE
bagging_mse <- mean((predict_bag - test$HeartDisease)^2) 

#Over all correct:
overall_bag <- (confm_bag[1,1]+confm_bag[2,2])/sum(confm_bag)

kable(confm_bag) #confusion matrix
overall_bag #over all correct


#Visulizaton of bagging
VI <- data.frame(var=names(test[,-1]), imp=varImp(bagging))
VI
#sort variable importance descending
VI_plot <- VI[order(VI$Overall, decreasing=TRUE),]

#visualize variable importance with horizontal bar plot
barplot(VI_plot$Overall,
        names.arg=rownames(VI_plot),
        horiz=TRUE,
        col='steelblue',
        xlab='Variable Importance')

#bagging
```

Test MSE is  0.1052255 for bagging






