@@ -1,70 +0,0 @@
---
title: "Boosting"
author: "Henrique"
output: html_notebook
---

```{r}

train <- read.csv("train.csv")
test <- read.csv("test.csv")
library(gbm)
library(caret)

set.seed(445)






```



```{r}


train$ChestPainType <- as.factor(train$ChestPainType)
train$Sex <- as.factor(train$Sex)
train$FastingBS <- as.factor(train$FastingBS)
train$RestingECG <- as.factor(train$RestingECG)
train$ExerciseAngina <- as.factor(train$ExerciseAngina)
train$ST_Slope <- as.factor(train$ST_Slope)


test$ChestPainType <- as.factor(test$ChestPainType)
test$Sex <- as.factor(test$Sex)
test$FastingBS <- as.factor(test$FastingBS)
test$RestingECG <- as.factor(test$RestingECG)
test$ExerciseAngina <- as.factor(test$ExerciseAngina)
test$ST_Slope <- as.factor(test$ST_Slope)



set.seed(445)




oob = trainControl(method = "oob")
cv_5 = trainControl(method = "cv", number = 5)

gbm_grid =  expand.grid(interaction.depth = 1:5,
                        n.trees = (1:5) * 200,
                        shrinkage = c(0.01,0.015,0.1),
                        n.minobsinnode = 10)


seat_gbm_tune = train(as.factor(HeartDisease) ~ ., data = train,
                      method = "gbm",
                      trControl = cv_5,
                      verbose = FALSE,
                      tuneGrid = gbm_grid)


plot(seat_gbm_tune)

```


```{r}
boost <- gbm(HeartDisease~.,data=train,n.trees=600,shrinkage=0.01,interaction.depth = 2 ,distribution = "bernoulli")


boostpred = ifelse(predict(boost,test, n.trees = 500, "response") > 0.5, 
                             "1", "0")

confm2<-table(predicted = boostpred, actual = test$HeartDisease)
confm2
error<-(confm2[1,1]+confm2[2,2])/sum(confm2)
error
```



```{r}
summa<-summary(boost)
```




```{r}
ggplot(summa)+geom_col(aes(x=var,y=rel.inf,fill=var))+coord_flip()+labs(title="Variable Importance",y=" Mean decrease in Accuracy", x= " Variable")+scale_y_continuous(labels = scales::percent_format())+guides(fill="none")
```