---
title: "KNN Model"
author: "Oriana Meldurm"
date: "12/5/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}


library(ISLR)
library(class)
library(tidyr)
library(knitr)
library(fastDummies)

train <- read.csv("train.csv")
test <- read.csv("test.csv")


train$ChestPainType <- as.factor(train$ChestPainType)
train$Sex <- as.factor(train$Sex)
train$FastingBS <- as.factor(train$FastingBS)
train$RestingECG <- as.factor(train$RestingECG)
train$ExerciseAngina <- as.factor(train$ExerciseAngina)
train$ST_Slope <- as.factor(train$ST_Slope)
train$HeartDisease <- as.factor(train$HeartDisease)


test$ChestPainType <- as.factor(test$ChestPainType)
test$Sex <- as.factor(test$Sex)
test$FastingBS <- as.factor(test$FastingBS)
test$RestingECG <- as.factor(test$RestingECG)
test$ExerciseAngina <- as.factor(test$ExerciseAngina)
test$ST_Slope <- as.factor(test$ST_Slope)
test$HeartDisease <- as.factor(test$HeartDisease)

temp_train <- dummy_cols(train, select_columns = c("Sex", "ChestPainType", "RestingECG", "ST_Slope", "ExerciseAngina") )
temp_test <- dummy_cols(test, select_columns = c("Sex", "ChestPainType", "RestingECG", "ST_Slope", "ExerciseAngina"))

drops <- c("Sex", "ChestPainType", "RestingECG", "ST_Slope", "ExerciseAngina")
temp_train <- temp_train[, !(names(temp_train) %in% drops)]
temp_test <-temp_test[, !(names(temp_test) %in% drops)]

```

```{r}
#Select best number for k

set.seed(445)
library(caret)

#5 fold
trControl <- trainControl(method = "cv", number = 5)



fit <- train(as.factor(HeartDisease) ~.,
             method = "knn", 
             tuneGrid = expand.grid(k = 1:100), 
             trControl = trControl, 
             metric = "Accuracy", 
             data = temp_train)

fit
```

The best accuracy comes from a k of 23 with and accuracy of 0.6878024. Technically both k=1 and k=4 have higher accuracy, but we are avoiding using as any outlines would create a skew for k=1 and in certain types of classification problems, our research shower it was better to avoid using an odd number as this can tie votes. 

```{r}



#trainknn <- temp_train[-temp_train$HeartDisease]
#testknn <- test[-test$HeartDisease]


num_k <- seq(1:100)

my_cv <- knn.cv(temp_train, temp_train$HeartDisease, k=num_k)



knn_pred_1 <- knn(temp_train, temp_test, temp_train$HeartDisease, k=23)

confm_knn_1<-table(knn_pred_1,test$HeartDisease)

overall_knn_1 <- (confm_knn_1[1,1]+confm_knn_1[2,2])/sum(confm_knn_1)


overall_knn_1

 #confusion matrix
kable(confm_knn_1)
mean(knn_pred_1 !=test$HeartDisease)

```










