---
title: "RandomForest"
author: "Henrique Rio"
date: "12/5/2021"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(randomForest)
train<-read.csv("train.csv")
test<-read.csv("test.csv")




options(repos='http://cran.rstudio.org')
have.packages <- installed.packages()
cran.packages <- c('devtools','plotrix','randomForest','tree')
to.install <- setdiff(cran.packages, have.packages[,1])
if(length(to.install)>0) install.packages(to.install)

library(devtools)
if(!('reprtree' %in% installed.packages())){
  install_github('araastat/reprtree')
}
for(p in c(cran.packages, 'reprtree')) eval(substitute(library(pkg), list(pkg=p)))


set.seed(445)

library(leaps)
library(ISLR)
library(tidyverse) 
library(knitr)
library(glmnet) # package for lasso and ridge regression
library(pls)
library(ISLR)
library(ggpubr)
library(MASS)
library(splines)
library(gam)
library(tree)
library(randomForest)
library(gbm)
library(caret)
```


```{r}
library(reprtree)

train$ChestPainType <- as.factor(train$ChestPainType)
train$Sex <- as.factor(train$Sex)
train$FastingBS <- as.factor(train$FastingBS)
train$RestingECG <- as.factor(train$RestingECG)
train$ExerciseAngina <- as.factor(train$ExerciseAngina)
train$ST_Slope <- as.factor(train$ST_Slope)
train$HeartDisease <- as.factor(train$HeartDisease)


test$ChestPainType <- as.factor(test$ChestPainType)
test$Sex <- as.factor(test$Sex)
test$FastingBS <- as.factor(test$FastingBS)
test$RestingECG <- as.factor(test$RestingECG)
test$ExerciseAngina <- as.factor(test$ExerciseAngina)
test$ST_Slope <- as.factor(test$ST_Slope)
test$HeartDisease <- as.factor(test$HeartDisease)
```


```{r}
rf_fit <- randomForest(as.factor(HeartDisease) ~ ., data = train, mtry = sqrt(ncol(train) - 1), importance = TRUE, type= "classification")

true <- test$HeartDisease
rf <- predict(rf_fit,test,type="class")



confm2<-table(predicted=rf,True=true)
confm2


paste("the overall fraction of correct predictions in the test dataset is :",(confm2[1,1]+confm2[2,2])/sum(confm2))
```

```{r}
print(rf_fit)
```






```{r}

reptree <- ReprTree(rf_fit, train, metric='d2')

```
```{r}

reptree$trees
plot(reptree, index=1)

```



```{r}




tree1 <- tree(HeartDisease~.,data= train)


plot(tree1)
text(tree1)

tree

```

```{r}
set.seed(445)

treet = predict(tree1, test, type = "class")

table(predicted = treet, actual = test$HeartDisease)

```

Overall test error rate (%83)

https://stats.stackexchange.com/questions/41443/how-to-actually-plot-a-sample-tree-from-randomforestgettree



Identifying representative trees from ensembles
Banerjee, Mousumi ; Ding, Ying ; Noone, Anne-Michelle
Chichester, UK: John Wiley & Sons, Ltd
Statistics in medicine, 2012-07-10, Vol.31 (15), p.1601-1616
